name: Example Python Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  check-app:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Listar todos los ficheros de la raiz
      run: ls -la
    - name: Instalar Python3
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Instalar librerias de pip
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Control de formato con Flake8
      run: |
        flake8 . --exit-zero --statistics # exit-zero devuelve error en caso de no superar el test de formato
    - name: Control de errores en escritura de codigo con Pylint
      run: |
        pylint ./src/main/
    - name: Ejecucion de tests con Pytest
      run: |
        pytest